### ISSUE TITLE
WIN - Error in set altitudemode

### ISSUE THREAD

**Issue by MrMaguN** [pdfinn/flightplan2litchimission#4]
I tried following the Quide for Windows and did manage to create the CSV using the tool. 
However when I try to import it in Mission hub I get the error "Error: invalid altitude mode for waypoint 1 (accepted values are 0 for AboveTakeOff or 1 for AboveGround)".

In the csv file the "altitudemode" file is set to 1 but I still get the error.

I then tried to manually change some values in the csv to make it work and after changing "actiontype1" from -1 to 1 the error stopped and it seems to load the csv into misson hub without errors.

I've added a csv file with the original and modified output as an example with a few waypoints:

[example_flight.xlsx](https://github.com/user-attachments/files/16691454/example_flight.xlsx)

So it seems like to me that "actiontype1" is working as "altitudemode" in the csv? 
I still have not yet tested if this works in the field as I'm new to Litchi and were about to test it out.

**Comment by pdfinn** [comment]
Thanks for bringing this to my attention and for the helpful debugging work.  Yes, actiontype was incorrectly being parsed to a negative value.  It should be 1 as this the action for taking a photo.  I've verified the output and also checked that the .csv is loading correctly into the Litchi mission manager.  I've uploaded new binaries.
